version: "3"
services:
  ubuntet:
    image: ubuntu
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
