version: "3"
services:
  colors:
    build:
      context: ./ColorsWebService
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ConnectionSettings__ConnectionString: "Data Source=sqlserver;User Id=sa;Password=X1nGuXunG1;Initial Catalog=Colors;Trusted_Connection=False;MultipleActiveResultSets=true"
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "X1nGuXunG1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
  web:
    build:
      context: ./espantApp
    ports:
      - "8080:80"
    environment:
      COLORS: "http://colors"
    depends_on:
      - colors
    restart: always
