version: "3.3"
services:
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: ies2010!
      MYSQL_DATABASE: Prova
      MYSQL_USER: jo
      MYSQL_PASSWORD: patata
  data-creator:
    image: utrescu/data-creator
    environment:
      DATABASE_NAME: Prova
      DATABASE_USER: jo
      DATABASE_PASSWORD: patata
      DATABASE_HOST: db
    depends_on:
      - db
